taskJDP190502-5
pplutap/JDP-1905-02 pull request #12
Opened 2019-06-02 10:54 UTC by aleksandra4991

2019-06-02 13:34 UTC, interceptor2048 requested changes

2019-06-02 13:34 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return new ArrayList<>(Arrays.asList(firstOrder,secondOrder));
wcięcia

2019-06-03 20:58 UTC, interceptor2048 approved these changes

2019-06-03 21:04 UTC, merged

2019-06-03 21:09 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +        return new ArrayList<>(Arrays.asList(firstOrder,secondOrder));
Brakuje wcięcia