taskJDP190502-14
pplutap/JDP-1905-02 pull request #29
Opened 2019-06-07 13:10 UTC by aleksandra4991

Jeśli będzie ok, to proszę osobę, która skomentuje,żeby w assignees oznaczyła mentorów :)

2019-06-07 15:08 UTC, lukechaj requested changes
O ile dobrze rozumiem to co widać cart.spec.json to zwrócona lista produktów. Czyli trzeba usunąć pola name, description i price.

2019-06-08 15:40 UTC, aawoznia26 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> -        //this.order = order;
@aleksandra4991 Zastanawia mnie tylko dlaczego konstruktor Cart zawiera listę produktów, a konstruktor CartDto cartId i group id? Group jest elementem product. Czy te konstruktory nie powinny zawierać takich samych atrybutów?

2019-06-08 16:13 UTC, Luke1024 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> -        //this.order = order;
Jeśli chodzi o konstruktor Cart według mnie nie powinno go być. (w sensie tylko bezparametrowy). W tej chwili nie potrzebujemy cardDto w ogóle.

2019-06-09 08:43 UTC, Luke1024 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> -        //this.order = order;
W sumie update, brak parametrów przekazywanych do konstruktora. Natomiast konstruktor Cart powinien tworzyć pustą listę produktów.

2019-06-09 12:29 UTC, aawoznia26 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> -        //this.order = order;
@aleksandra4991 @Luke1024 Zgadzam się, że przy obecności CartProductAdderDto.java i CartProductDeleterDto.java  CartDto nie jest potrzebny, czyli trzeba go usunąć

2019-06-09 20:56 UTC, aawoznia26 approved these changes

2019-06-10 06:54 UTC, interceptor2048 approved these changes

2019-06-10 07:25 UTC, lukechaj approved these changes

2019-06-10 07:26 UTC, merged