Jdp190502 22
pplutap/JDP-1905-02 pull request #46
Opened 2019-06-20 07:09 UTC by aleksandra4991

2019-06-20 07:46 UTC, lukechaj approved these changes

2019-06-21 06:47 UTC, pplutap requested changes

2019-06-21 06:47 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    private static final GroupDto food = new GroupDto("Food");
Stałe nie są potrzebne

2019-06-21 06:47 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    GroupService groupService;
Brakuje `private`

2019-06-21 06:47 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    GroupMapper groupMapper;
Brakuje `private`

2019-06-21 06:47 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/controller/GroupControllerTest.java
> +
Brak implementacji

2019-06-22 08:20 UTC, pplutap approved these changes

2019-06-22 10:13 UTC, merged