Jdp190502 25
pplutap/JDP-1905-02 pull request #48
Opened 2019-06-21 18:02 UTC by jalowiec

2019-06-22 07:31 UTC, aleksandra4991 reviewed
Jest ok :)

2019-06-22 07:44 UTC, lukechaj approved these changes

2019-06-22 08:25 UTC, pplutap requested changes

2019-06-22 08:25 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        UserDto userDto = userMapper.mapToUserDto(service.getUser(userId));
Nie ma konieczności pobierania usera, mapowania, ustawiania wartości w dto, kolejnego mapowania i zapisywania. Jest zbyt dużo operacji a można to wykonać odpowiednim zapytaniem w repository (metoda w serwisie oczywiście powinna istnieć) - https://www.baeldung.com/spring-data-jpa-query

2019-06-22 08:25 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        UserDto userDto = userMapper.mapToUserDto(service.getUser(userId));
Podobnie jak w komentarzu wyżej

2019-06-22 08:25 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/controller/UserControllerTest.java
> +    private UserController userController;
Jeśli chcesz przetestować kontroler to należy użyć obiektu `MockMvc` i adnotacji `@WebMvcTest` nad klasą z testem

2019-06-23 13:23 UTC, pplutap approved these changes

2019-06-23 13:23 UTC, merged